#!/bin/sh
set -e

echo "=========================================="
echo "Fresh Install: South African Real Estate CRM"
echo "=========================================="

cd /app/nocobase

echo "Step 1: Creating database tables..."
psql "$DATABASE_URL" << 'PSQL' 2>/dev/null || true

-- Create CRM tables with proper structure
CREATE TABLE IF NOT EXISTS "crm_leads" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "first_name" varchar(255),
  "last_name" varchar(255),
  "email" varchar(255),
  "phone" varchar(255),
  "status" varchar(255) DEFAULT 'new',
  "source" varchar(255),
  "budget_min" decimal,
  "budget_max" decimal,
  "preferred_location" varchar(255),
  "property_type" varchar(255),
  "bedrooms_required" integer,
  "rsa_id" varchar(255),
  "fica_status" varchar(50) DEFAULT 'pending',
  "notes" text,
  "created_at" timestamptz DEFAULT NOW(),
  "updated_at" timestamptz DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS "crm_properties" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(255),
  "address" varchar(255),
  "suburb" varchar(255),
  "city" varchar(255) DEFAULT 'Johannesburg',
  "province" varchar(255) DEFAULT 'Gauteng',
  "postal_code" varchar(255),
  "property_type" varchar(255),
  "status" varchar(255) DEFAULT 'available',
  "price" decimal,
  "bedrooms" integer,
  "bathrooms" integer,
  "description" text,
  "features" text,
  "created_at" timestamptz DEFAULT NOW(),
  "updated_at" timestamptz DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS "crm_deals" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(255),
  "contact_id" varchar(255),
  "property_id" varchar(255),
  "stage" varchar(255) DEFAULT 'prospecting',
  "value" decimal,
  "commission" decimal,
  "probability" integer,
  "expected_close_date" date,
  "assigned_to" varchar(255),
  "notes" text,
  "created_at" timestamptz DEFAULT NOW(),
  "updated_at" timestamptz DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS "crm_contacts" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "first_name" varchar(255),
  "last_name" varchar(255),
  "email" varchar(255),
  "phone" varchar(255),
  "mobile" varchar(255),
  "address" varchar(255),
  "city" varchar(255),
  "suburb" varchar(255),
  "type" varchar(255) DEFAULT 'prospect',
  "company" varchar(255),
  "source" varchar(255),
  "assigned_to" varchar(255),
  "notes" text,
  "do_not_call" boolean DEFAULT false,
  "do_not_email" boolean DEFAULT false,
  "created_at" timestamptz DEFAULT NOW(),
  "updated_at" timestamptz DEFAULT NOW()
);

PSQL

echo "Step 2: Registering collections in NocoBase..."
yarn nocobase db:sync --quick 2>/dev/null || true

echo "Step 3: Adding collections to NocoBase..."
yarn pm add @nocobase/plugin-collection-manager --quick 2>/dev/null || true

echo "Step 4: Creating menu items..."
psql "$DATABASE_URL" << 'PSQL' 2>/dev/null || true

-- Create menu items for CRM collections
INSERT INTO "ui_schemas" ("name", "ui_schema", "created_at", "updated_at") VALUES
('crm_menu', '{
  "type": "void",
  "title": "CRM",
  "name": "crm",
  "icon": "ShopOutlined",
  "x-designer": {"placement": "sidebar"},
  "children": [
    {
      "type": "page",
      "title": "Leads",
      "name": "crm_leads",
      "icon": "UserOutlined",
      "path": "/admin/crm/leads",
      "x-resource": "crm_leads",
      "x-decorator": "APIClientDataBlock",
      "x-decorator-props": {
        "resource": "crm_leads",
        "action": "list",
        "params": {"pageSize": 20}
      }
    },
    {
      "type": "page",
      "title": "Properties",
      "name": "crm_properties",
      "icon": "HomeOutlined",
      "path": "/admin/crm/properties",
      "x-resource": "crm_properties",
      "x-decorator": "APIClientDataBlock",
      "x-decorator-props": {
        "resource": "crm_properties",
        "action": "list",
        "params": {"pageSize": 20}
      }
    },
    {
      "type": "page",
      "title": "Deals",
      "name": "crm_deals",
      "icon": "PercentageOutlined",
      "path": "/admin/crm/deals",
      "x-resource": "crm_deals",
      "x-decorator": "APIClientDataBlock",
      "x-decorator-props": {
        "resource": "crm_deals",
        "action": "list",
        "params": {"pageSize": 20}
      }
    },
    {
      "type": "page",
      "title": "Contacts",
      "name": "crm_contacts",
      "icon": "TeamOutlined",
      "path": "/admin/crm/contacts",
      "x-resource": "crm_contacts",
      "x-decorator": "APIClientDataBlock",
      "x-decorator-props": {
        "resource": "crm_contacts",
        "action": "list",
        "params": {"pageSize": 20}
      }
    }
  ]
}', NOW(), NOW()) ON CONFLICT ("name") DO NOTHING;

PSQL

echo "Step 5: Setting up collection permissions..."
psql "$DATABASE_URL" << 'PSQL' 2>/dev/null || true

-- Grant permissions for collections
GRANT SELECT, INSERT, UPDATE, DELETE ON "crm_leads" TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON "crm_properties" TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON "crm_deals" TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON "crm_contacts" TO authenticated;

-- Grant read access to anonymous users
GRANT SELECT ON "crm_leads" TO anon;
GRANT SELECT ON "crm_properties" TO anon;
GRANT SELECT ON "crm_deals" TO anon;
GRANT SELECT ON "crm_contacts" TO anon;

PSQL

echo "=========================================="
echo "✅ CRM Installation Complete!"
echo "=========================================="
echo ""
echo "Your CRM collections are now available:"
echo "- Leads (with RSA ID and FICA status)"
echo "- Properties (with South African locations)"
echo "- Deals (sales opportunities)"
echo "- Contacts (contact management)"
echo ""
echo "The CRM menu should appear in your sidebar."
echo "If it doesn't appear immediately, try refreshing your browser."
echo ""
echo "Visit: https://omnia-app.up.railway.app/admin"
echo "=========================================="

exit 0
