#!/bin/sh
set -e

echo "=========================================="
echo "Installing South African Real Estate CRM"
echo "=========================================="

cd /app/nocobase

psql "$DATABASE_URL" << 'PSQL' 2>/dev/null || true

-- Create CRM tables
CREATE TABLE IF NOT EXISTS "crm_leads" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "first_name" varchar(255),
  "last_name" varchar(255),
  "full_name" varchar(255),
  "email" varchar(255),
  "phone" varchar(255),
  "mobile" varchar(255),
  "company" varchar(255),
  "status" varchar(255) DEFAULT 'new',
  "source" varchar(255),
  "budget_min" decimal,
  "budget_max" decimal,
  "preferred_location" varchar(255),
  "property_type" varchar(255),
  "bedrooms_required" integer,
  "timeline" varchar(255),
  "rating" integer,
  "rsa_id" varchar(255),
  "tax_number" varchar(255),
  "fica_status" varchar(50) DEFAULT 'pending',
  "notes" text,
  "created_at" timestamptz DEFAULT NOW(),
  "updated_at" timestamptz DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS "crm_properties" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(255),
  "address" varchar(255),
  "suburb" varchar(255),
  "city" varchar(255) DEFAULT 'Johannesburg',
  "province" varchar(255) DEFAULT 'Gauteng',
  "postal_code" varchar(255),
  "property_type" varchar(255),
  "status" varchar(255) DEFAULT 'available',
  "price" decimal,
  "bedrooms" integer,
  "bathrooms" integer,
  "garages" integer,
  "erf_size" integer,
  "floor_size" integer,
  "pool" boolean DEFAULT false,
  "garden" boolean DEFAULT false,
  "security" boolean DEFAULT false,
  "description" text,
  "features" jsonb,
  "listing_date" timestamptz,
  "created_at" timestamptz DEFAULT NOW(),
  "updated_at" timestamptz DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS "crm_deals" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(255),
  "lead_id" bigint,
  "property_id" bigint,
  "stage" varchar(255) DEFAULT 'qualification',
  "value" decimal,
  "commission_rate" decimal DEFAULT 3.0,
  "commission_amount" decimal,
  "fica_checklist" jsonb,
  "fica_status" varchar(50) DEFAULT 'pending',
  "notes" text,
  "expected_close_date" timestamptz,
  "actual_close_date" timestamptz,
  "created_at" timestamptz DEFAULT NOW(),
  "updated_at" timestamptz DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS "crm_contacts" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "first_name" varchar(255),
  "last_name" varchar(255),
  "full_name" varchar(255),
  "email" varchar(255),
  "phone" varchar(255),
  "mobile" varchar(255),
  "rsa_id" varchar(255),
  "address" varchar(255),
  "suburb" varchar(255),
  "city" varchar(255),
  "province" varchar(255) DEFAULT 'Gauteng',
  "postal_code" varchar(255),
  "fica_status" varchar(50) DEFAULT 'pending',
  "notes" text,
  "created_at" timestamptz DEFAULT NOW(),
  "updated_at" timestamptz DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS "crm_suburbs" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(255),
  "city" varchar(255) DEFAULT 'Johannesburg',
  "province" varchar(255) DEFAULT 'Gauteng',
  "latitude" decimal,
  "longitude" decimal,
  "average_price" decimal,
  "median_price" decimal,
  "total_listings" integer DEFAULT 0,
  "created_at" timestamptz DEFAULT NOW(),
  "updated_at" timestamptz DEFAULT NOW()
);

-- Insert sample suburbs
INSERT INTO "crm_suburbs" ("name", "city", "province", "latitude", "longitude", "average_price", "median_price", "total_listings") VALUES
('Sandton', 'Johannesburg', 'Gauteng', -26.1076, 28.0567, 3500000, 2800000, 45),
('Midrand', 'Johannesburg', 'Gauteng', -25.9894, 28.1333, 1850000, 1500000, 32),
('Fourways', 'Johannesburg', 'Gauteng', -26.0172, 27.9822, 2200000, 1800000, 28),
('Bryanston', 'Johannesburg', 'Gauteng', -26.0694, 28.0167, 2800000, 2200000, 35),
('Randburg', 'Johannesburg', 'Gauteng', -26.1667, 27.9833, 1500000, 1200000, 22)
ON CONFLICT DO NOTHING;

-- Insert sample leads
INSERT INTO "crm_leads" ("first_name", "last_name", "email", "phone", "status", "source", "budget_min", "budget_max", "preferred_location", "property_type", "rsa_id") VALUES
('John', 'Smith', 'john.smith@email.com', '+27-82-123-4567', 'qualified', 'Website', 2000000, 3500000, 'Sandton', 'House', '8001011234089'),
('Maria', 'Van der Merwe', 'maria.vdm@email.com', '+27-83-234-5678', 'new', 'Referral', 1500000, 2500000, 'Midrand', 'Townhouse', '8502021234089')
ON CONFLICT DO NOTHING;

-- Insert sample properties
INSERT INTO "crm_properties" ("title", "address", "suburb", "property_type", "status", "price", "bedrooms", "bathrooms") VALUES
('Modern Family Home', '123 Oak Street', 'Sandton', 'House', 'available', 3450000, 4, 3),
('Luxury Townhouse', '45 Maple Avenue', 'Midrand', 'Townhouse', 'available', 1850000, 3, 2)
ON CONFLICT DO NOTHING;

-- Add collections to NocoBase
INSERT INTO "collections" (name, title, "dataSourceKey", "schema", "template", "engine", "syncMode", "createdAt", "updatedAt") VALUES
('crm_leads', 'Leads', 'main', '{"name":"crm_leads"}', 'general', 'InMemory', false, NOW(), NOW()),
('crm_properties', 'Properties', 'main', '{"name":"crm_properties"}', 'general', 'InMemory', false, NOW(), NOW()),
('crm_deals', 'Deals', 'main', '{"name":"crm_deals"}', 'general', 'InMemory', false, NOW(), NOW()),
('crm_contacts', 'Contacts', 'main', '{"name":"crm_contacts"}', 'general', 'InMemory', false, NOW(), NOW()),
('crm_suburbs', 'Suburbs', 'main', '{"name":"crm_suburbs"}', 'general', 'InMemory', false, NOW(), NOW())
ON CONFLICT (name) DO NOTHING;

-- Add fields for crm_leads
INSERT INTO "collection_fields" ("collectionName", "name", "type", "interface", "title", "dataType", "uiSchema", "defaultValue", "creator", "createdAt", "updatedAt") VALUES
('crm_leads', 'first_name', 'string', 'input', 'First Name', 'VARCHAR', '{"en-US":{"title":"First Name"}}', null, 'system', NOW(), NOW()),
('crm_leads', 'last_name', 'string', 'input', 'Last Name', 'VARCHAR', '{"en-US":{"title":"Last Name"}}', null, 'system', NOW(), NOW()),
('crm_leads', 'email', 'string', 'email', 'Email', 'VARCHAR', '{"en-US":{"title":"Email"}}', null, 'system', NOW(), NOW()),
('crm_leads', 'phone', 'string', 'phone', 'Phone', 'VARCHAR', '{"en-US":{"title":"Phone"}}', null, 'system', NOW(), NOW()),
('crm_leads', 'status', 'string', 'select', 'Status', 'VARCHAR', '{"en-US":{"title":"Status","enum":[{"label":"New","value":"new"},{"label":"Contacted","value":"contacted"},{"label":"Qualified","value":"qualified"}]}}', 'new', 'system', NOW(), NOW())
ON CONFLICT DO NOTHING;

-- Add fields for crm_properties
INSERT INTO "collection_fields" ("collectionName", "name", "type", "interface", "title", "dataType", "uiSchema", "defaultValue", "creator", "createdAt", "updatedAt") VALUES
('crm_properties', 'title', 'string', 'input', 'Title', 'VARCHAR', '{"en-US":{"title":"Title"}}', null, 'system', NOW(), NOW()),
('crm_properties', 'address', 'string', 'input', 'Address', 'VARCHAR', '{"en-US":{"title":"Address"}}', null, 'system', NOW(), NOW()),
('crm_properties', 'price', 'decimal', 'number', 'Price (ZAR)', 'DECIMAL', '{"en-US":{"title":"Price (ZAR)"}}', null, 'system', NOW(), NOW()),
('crm_properties', 'status', 'string', 'select', 'Status', 'VARCHAR', '{"en-US":{"title":"Status","enum":[{"label":"Available","value":"available"},{"label":"Sold","value":"sold"}]}}', 'available', 'system', NOW(), NOW())
ON CONFLICT DO NOTHING;

-- Add CRM menu item to sidebar
DELETE FROM "ui_schemas" WHERE "id" = 9001;

INSERT INTO "ui_schemas" ("id", "uiSchema", "createdAt", "updatedAt") VALUES
(9001, '{"type":"void","version":"2.0","x-uid":"crm-menu","x-designer":{"placement":"sidebar"},"title":"CRM","name":"crm","icon":"ShopOutlined","children":[{"version":"2.0","x-uid":"crm-leads","x-designer":{"placement":"inline"},"type":"page","title":"Leads","icon":"UserOutlined","name":"crm_leads","path":"/crm/leads","children":[]},{"version":"2.0","x-uid":"crm-properties","x-designer":{"placement":"inline"},"type":"page","title":"Properties","icon":"HomeOutlined","name":"crm_properties","path":"/crm/properties","children":[]},{"version":"2.0","x-uid":"crm-deals","x-designer":{"placement":"inline"},"type":"page","title":"Deals","icon":"PercentageOutlined","name":"crm_deals","path":"/crm/deals","children":[]}]}', NOW(), NOW());

PSQL

echo "CRM installation complete!"
echo ""
echo "To view your CRM data:"
echo "1. Go to Settings > Data Source Manager > Main Database > Collections"
echo "2. You should see: Leads, Properties, Deals, Contacts, Suburbs"
echo "3. Click on any collection and configure the UI to add to sidebar"

exit 0
